// blueprints/molecule-capsule/m-chemx-badge/m-chemx-badge.svelte
<script lang="ts">
  import type { MChemxBadgeProps } from './types';

  export const resolveGradeClass = (grade: string): string => {
    const g = grade.toUpperCase();
    const isGradeA = Boolean(g.startsWith('A'));
    if (isGradeA) return 'm-chemx-badge__grade--a';
    const isGradeB = Boolean(g.startsWith('B'));
    if (isGradeB) return 'm-chemx-badge__grade--b';
    const isGradeC = Boolean(g.startsWith('C'));
    if (isGradeC) return 'm-chemx-badge__grade--c';
    const isGradeD = Boolean(g.startsWith('D'));
    if (isGradeD) return 'm-chemx-badge__grade--d';
    return 'm-chemx-badge__grade--f';
  };

  let {
    label = 'AI Slop cleaned with Chemical X',
    grade = 'A+',
    href = 'https://chemicalx.xophz.com',
    reportUrl = undefined,
    className = ''
  } = $props<MChemxBadgeProps>();

  const targetHref = $derived(reportUrl || href);
  const gradeClass = $derived(resolveGradeClass(grade));
</script>

<a
  href={targetHref}
  target="_blank"
  rel="noopener noreferrer"
  class="m-chemx-badge {className}"
  title="Verified by Chemical X Molecular Architecture Protocol"
>
  <span class="m-chemx-badge__dot"></span>
  <span class="m-chemx-badge__label">{label}</span>
  <span class="m-chemx-badge__grade {gradeClass}">[{grade}]</span>
</a>

// blueprints/molecule-capsule/m-chemx-badge/m-chemx-badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { MChemxBadgeProps } from './types';

const props = withDefaults(defineProps<MChemxBadgeProps>(), {
  label: 'AI Slop cleaned with Chemical X',
  grade: 'A+',
  href: 'https://chemicalx.xophz.com',
  reportUrl: undefined,
  className: ''
});

// 1. Composables & Stores

// 2. Reactive Primitives

// 3. Computed State
const targetHref = computed(() => props.reportUrl || props.href);
const gradeClass = computed(() => {
  const g = props.grade.toUpperCase();
  const isGradeA = g.startsWith('A');
  if (isGradeA) return 'm-chemx-badge__grade--a';
  const isGradeB = g.startsWith('B');
  if (isGradeB) return 'm-chemx-badge__grade--b';
  const isGradeC = g.startsWith('C');
  if (isGradeC) return 'm-chemx-badge__grade--c';
  const isGradeD = g.startsWith('D');
  if (isGradeD) return 'm-chemx-badge__grade--d';
  return 'm-chemx-badge__grade--f';
});
</script>

<template>
  <a
    :href="targetHref"
    target="_blank"
    rel="noopener noreferrer"
    class="m-chemx-badge"
    :class="className"
    title="Verified by Chemical X Molecular Architecture Protocol"
  >
    <span class="m-chemx-badge__dot" />
    <span class="m-chemx-badge__label">{{ label }}</span>
    <span class="m-chemx-badge__grade" :class="gradeClass">[{{ grade }}]</span>
  </a>
</template>
