// blueprints/atoms/a-button.svelte
<script lang="ts">
  export interface AtomButtonProps {
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
    ariaLabel?: string;
    variant?: 'primary' | 'ghost' | 'glass';
    class?: string;
    onclick?: (e: MouseEvent) => void;
    children?: import('svelte').Snippet;
  }

  let {
    type = 'button',
    disabled = false,
    ariaLabel = undefined,
    variant = 'primary',
    class: className = '',
    onclick,
    children
  } = $props<AtomButtonProps>();
</script>

<button
  {type}
  {disabled}
  aria-label={ariaLabel}
  class="a-button cursor-pointer {className}"
  data-variant={variant}
  {onclick}
>
  {@render children?.()}
</button>

// blueprints/atoms/a-button.tsx
import React from 'react';

export interface AtomButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'ghost' | 'glass';
  ariaLabel?: string;
  children?: React.ReactNode;
}

export const AtomButton: React.FC<AtomButtonProps> = ({
  type = 'button',
  disabled = false,
  ariaLabel,
  variant = 'primary',
  children,
  className = '',
  onClick,
  ...rest
}) => {
  const rootClass = `a-button cursor-pointer ${className}`.trim();

  return (
    <button
      type={type}
      disabled={disabled}
      aria-label={ariaLabel}
      className={rootClass}
      data-variant={variant}
      onClick={onClick}
      {...rest}
    >
      {children}
    </button>
  );
};

export default AtomButton;
