// blueprints/molecule-capsule/m-sample-card.vue
<script setup lang="ts">
import { computed } from 'vue';
import AButton from '../../atoms/a-button.vue';
import type { MSampleCardProps, SampleCardBadgeDescriptor } from './types';

const props = withDefaults(defineProps<MSampleCardProps>(), {
  subtitle: undefined,
  status: 'active',
  onAction: undefined
});

const isHighValue = computed(() => props.value > 1000);

const badge = computed((): SampleCardBadgeDescriptor => {
  if (props.status !== 'active') {
    return {
      text: props.status,
      className: 'm-sample-card__badge m-sample-card__badge--archived'
    };
  }
  if (isHighValue.value) {
    return {
      text: props.status,
      className: 'm-sample-card__badge m-sample-card__badge--high-value'
    };
  }
  return {
    text: props.status,
    className: 'm-sample-card__badge m-sample-card__badge--standard'
  };
});

const handleActionClick = () => {
  if (props.onAction) props.onAction();
};
</script>

<template>
  <div class="m-sample-card">
    <div class="m-sample-card__header">
      <div class="m-sample-card__title-group">
        <h3 class="m-sample-card__title">{{ title }}</h3>
        <p v-if="subtitle" class="m-sample-card__subtitle">{{ subtitle }}</p>
      </div>
      <span :class="badge.className">{{ badge.text }}</span>
    </div>
    <div class="m-sample-card__body">
      <div class="m-sample-card__value">
        ${{ value.toLocaleString() }}
      </div>
      <AButton
        v-if="onAction"
        class="m-sample-card__action"
        @click="handleActionClick"
      >
        Action
      </AButton>
    </div>
  </div>
</template>

// blueprints/molecule-capsule/m-sample-card.svelte
<script lang="ts">
  import AButton from '../atoms/a-button.svelte';
  import type { MSampleCardProps, SampleCardBadgeDescriptor } from './types';

  let {
    title,
    subtitle = undefined,
    value,
    status = 'active',
    onAction = undefined
  } = $props<MSampleCardProps>();

  const isHighValue = $derived(value > 1000);

  const badge = $derived.by((): SampleCardBadgeDescriptor => {
    if (status !== 'active') {
      return {
        text: status,
        className: 'm-sample-card__badge m-sample-card__badge--archived'
      };
    }
    if (isHighValue) {
      return {
        text: status,
        className: 'm-sample-card__badge m-sample-card__badge--high-value'
      };
    }
    return {
      text: status,
      className: 'm-sample-card__badge m-sample-card__badge--standard'
    };
  });
</script>

<div class="m-sample-card">
  <div class="m-sample-card__header">
    <div class="m-sample-card__title-group">
      <h3 class="m-sample-card__title">{title}</h3>
      {#if subtitle}
        <p class="m-sample-card__subtitle">{subtitle}</p>
      {/if}
    </div>
    <span class={badge.className}>{badge.text}</span>
  </div>
  <div class="m-sample-card__body">
    <div class="m-sample-card__value">
      ${value.toLocaleString()}
    </div>
    {#if onAction}
      <AButton
        class="m-sample-card__action"
        onclick={onAction}
      >
        Action
      </AButton>
    {/if}
  </div>
</div>
